export const predefinedColors = [
  { code: "#EC4899", name: "pink", className: "pink-500" },
  { code: "#D946EF", name: "fuchsia", className: "fuchsia-500" },
  { code: "#A855F7", name: "purple", className: "purple-500" },
  { code: "#8B5CF6", name: "violet", className: "violet-500" },
  { code: "#6366F1", name: "indigo", className: "indigo-500" },
  { code: "#3B82F6", name: "blue", className: "blue-500" },
  { code: "#0EA5E9", name: "sky", className: "sky-500" },
  { code: "#06B6D4", name: "cyan", className: "cyan-500" },
  { code: "#14B8A6", name: "teal", className: "teal-500" },
  { code: "#10B981", name: "emerald", className: "emerald-500" },
  { code: "#22C55E", name: "green", className: "green-500" },
  { code: "#84CC16", name: "lime", className: "lime-500" },
  { code: "#F59E0B", name: "amber", className: "amber-500" },
  { code: "#F97316", name: "orange", className: "orange-500" },
  { code: "#78716C", name: "warm gray", className: "warm-gray-500" },
  { code: "#737373", name: "gray", className: "gray-500" },
];
export const predefinedColorsSecondary = [
  { code: "#F9A8D4", name: "pink", className: "pink-300" },
  { code: "#F0ABFC", name: "fuchsia", className: "fuchsia-300" },
  { code: "#D8B4FE", name: "purple", className: "purple-300" },
  { code: "#C4B5FD", name: "violet", className: "violet-300" },
  { code: "#A5B4FC", name: "indigo", className: "indigo-300" },
  { code: "#93C5FD", name: "blue", className: "blue-300" },
  { code: "#7DD3FC", name: "sky", className: "sky-300" },
  { code: "#67E8F9", name: "cyan", className: "cyan-300" },
  { code: "#5EEAD4", name: "teal", className: "teal-300" },
  { code: "#6EE7B7", name: "emerald", className: "emerald-300" },
  { code: "#86EFAC", name: "green", className: "green-300" },
  { code: "#BEF264", name: "lime", className: "lime-300" },
  { code: "#FCD34D", name: "amber", className: "amber-300" },
  { code: "#FDBA74", name: "orange", className: "orange-300" },
  { code: "#D6D3D1", name: "warm gray", className: "warm-gray-300" },
  { code: "#D4D4D8", name: "gray", className: "gray-300" },
];

export const fonts = [
  "Helvetica Neue",
  "Proxima Nova",
  "Avenir",
  "Roboto",
  "Garamond",
  "Futura",
  "DIN",
  "Baskerville",
  "FF Meta",
  "Inter",
  "Merriweather",
  "Lobster",
  "Montserrat",
  "Open Sans",
  "Poppins",
  "Raleway",
  "Lato",
];

export * from "./html";
export * from "./prompts";
