export const prompts: Record<string, string> = {
  header: `You are a talented UI designer who specializes in creating structured content for landing pages. Your task is to generate a JSON object for the Header Section. Create a JSON object named "header" with keys for "logo" and "navigationMenuItems" (an array of menu 5 items). Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  hero: `You are a talented UI designer. Your task is to generate a JSON object for the Hero Section. Create a JSON object named "hero" with keys for "title", "description", "jumbotron" (background image description), and "cta" (call-to-action text). Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  features: `You are a skilled UI designer. Your mission is to design a JSON object for the Feature Section. Create a JSON object named "features" with keys for "feature_1", "feature_2", and "feature_3". Each feature should be a nested object with keys for "title", "icon", and "description". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  individualFeatures: `As a UI designer, design a JSON object for Individual Feature Sections. Create a JSON object named "individualFeatures" with keys for "feature_1", "feature_2", and "feature_3". Each feature should be a nested object with keys for "title", "description", "cta", and "backgroundImageDescription". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  testimonials: `Using your UI design skills, generate a JSON object for the Testimonial Section. Create a JSON object named "testimonials" with keys for "testimonial_1" and "testimonial_2". Each testimonial should be a nested object with keys for "name", "role", and "feedback". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  blog: `You are a proficient UI designer. Your task is to create a JSON object for the Blog Section. Design a JSON object named "blog" with keys for "post_1", "post_2", and "post_3". Each post should be a nested object with keys for "title" and "shortDescription". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  faq: `Leveraging your UI design expertise, craft a JSON object for the FAQ Section. Construct a JSON object named "faq" with keys for "question_1", "question_2", etc. Each question should be a nested object with keys for "question" and "answer". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  team: `As a top-tier UI designer, your challenge is to devise a JSON object for the Team Section. Design a JSON object named "team" with keys for "member_1", "member_2", and "member_3". Each member should be a nested object with keys for "name", "role", and "socialMediaLinks" (an array of social media platforms). Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  newsletter: `Your task, as a UI designer, is to create a JSON object for the Newsletter Subscription. Develop a JSON object named "newsletter" with keys for "title" and "cta". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  contactForm: `Employing your UI design capabilities, construct a JSON object for the Contact Form. Design a JSON object named "contactForm" with keys for "nameField", "emailField", and "messageField". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  map: `As an expert UI designer, you are tasked with generating a JSON object for the Map Section. Establish a JSON object named "map" with keys for "locationDescription" and "googleMapsAPIKey". Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
  footer: `Using your comprehensive UI design knowledge, craft a JSON object for the Footer Section. Construct a JSON object named "footer" with keys for "socialMediaLinks" (an array of social media platforms). Please ensure that each key-value pair contains only text. Format the JSON object for readability.`,
};

export const promptKeys = Object.keys(prompts);
